In [2]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2 = np.array([[1, 2, 3],[4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(arr2)

numpy.ndarray

In [6]:
arr3 = np.zeros((5,3))
arr4 = np.ones((5,3))
print(arr3)

print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arr5 = np.identity((5))
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
arr6 = np.arange(15)
print(arr6)

arr7 = np.arange(5,15)
print(arr7)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 5  6  7  8  9 10 11 12 13 14]


In [9]:
arr8 = np.linspace(10, 20, 10)
print(arr8)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [10]:
arr9 = arr8.copy()
print(arr9)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]
