In [14]:
import numpy as np

# 1D array example
arr_1d = np.array([1, 2, 3, 4, 5])  # Create a 1D array
print("1D array:")
print(arr_1d)
print("Dimension of 1D array:", arr_1d.ndim)

# 2D array example
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])  # Create a 2D array
print("\n2D array:")
print(arr_2d)
print("Dimension of 2D array:", arr_2d.ndim)

# 3D array example
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Create a 3D array
print("\n3D array:")
print(arr_3d)
print("Dimension of 3D array:", arr_3d.ndim)

# Reshape 1D array to shape (2, 3, 2)
arr = np.arange(12)  # Create a 1D array with 12 elements: [0, 1, ..., 11]
reshaped_arr = arr.reshape(2, 3, 2)  # Reshape to 2x3x2
print("\nReshaped 1D array to (2, 3, 2):")
print(reshaped_arr)
print("Shape of reshaped array:", reshaped_arr.shape)
print("Dimension of reshaped array:", reshaped_arr.ndim)

1D array:
[1 2 3 4 5]
Dimension of 1D array: 1

2D array:
[[1 2 3]
 [4 5 6]]
Dimension of 2D array: 2

3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimension of 3D array: 3

Reshaped 1D array to (2, 3, 2):
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Shape of reshaped array: (2, 3, 2)
Dimension of reshaped array: 3


In [15]:
list_a = range(100)
list_b = np.arange(100)

import sys

print("\nMemory usage:")
print(f"List (estimated): {sys.getsizeof(87)*len(list_a)} bytes")
print(f"NumPy array: {list_b.itemsize*list_b.size} bytes")


Memory usage:
List (estimated): 2800 bytes
NumPy array: 800 bytes


In [16]:
import numpy as np
array = np.array([1,2,3,4,5])
array = array * 2
print(array)

[ 2  4  6  8 10]


In [17]:
import numpy as np
array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                 [['J','K','L'],['M','N','O'],['P','Q','R']],
                 [['S','T','U'],['V','W','X'],['Y','Z',' ']]])
print(array.shape)
print(array.ndim)

(3, 3, 3)
3


In [18]:
import numpy as np
array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                 [['J','K','L'],['M','N','O'],['P','Q','R']],
                 [['S','T','U'],['V','W','X'],['Y','Z',' ']]])

print(array[0][2][1] + array[0][1][1] + array[1][0][2] + array[1][0][2] + array[1][1][2]) 

HELLO


In [19]:
import numpy as np
array = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

print(array[0:4:2])
print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[ 1  2  3  4]
 [ 9 10 11 12]]
2
(4, 4)
16
int64


In [20]:
import numpy as np
array = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

print("Columns:")
print("Column 0:",array[:,0])
print("Column 1:",array[:,1])
print("Column 2:",array[:,2])
print("Column 3:",array[:,3])



print("\nSelect specific rows and columns:\n", array[:2,:2])

Columns:
Column 0: [ 1  5  9 13]
Column 1: [ 2  6 10 14]
Column 2: [ 3  7 11 15]
Column 3: [ 4  8 12 16]

Select specific rows and columns:
 [[1 2]
 [5 6]]


In [21]:
import numpy as np
array = np.array([1,2,3])
print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)

print(np.sqrt(array))
print(np.exp(array))
print(np.log(array))


[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


# Rules for Broadcasting in NumPy
Broadcasting in NumPy follows these rules:
1. **If the arrays have different numbers of dimensions,** prepend 1s to the shape of the smaller array until both shapes have the same length.
2. **Arrays are compatible in a dimension if they have the same size or if one of them is 1.**
3. **Arrays can be broadcast together if they are compatible in all dimensions.**
4. **After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the input arrays.**
5. **If an array's dimension is 1, it is stretched to match the other array's size in that dimension.**

**Example:**
- Shape (3, 1) and (1, 4) can be broadcast to (3, 4).
- Shape (5, 4) and (1, 4) can be broadcast to (5, 4).

In [22]:
import numpy as np

# Broadcasting example: adding a 1D array to a 2D array
a = np.array([1, 2, 3])           # Shape: (3,)
b = np.array([[10], [20], [30]])  # Shape: (3, 1)

# NumPy automatically broadcasts 'a' to match the shape of 'b'
result = a + b

print("Array a:")
print(a)
print("\nArray b:")
print(b)
print("\nResult of broadcasting a + b:")
print(result)
print("Shape of result:", result.shape)

Array a:
[1 2 3]

Array b:
[[10]
 [20]
 [30]]

Result of broadcasting a + b:
[[11 12 13]
 [21 22 23]
 [31 32 33]]
Shape of result: (3, 3)


In [23]:
import numpy as np

array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(np.sum(array))  # Sum of all elements
print(np.mean(array))  # Mean of all elements
print(np.max(array))  # Maximum element
print(np.min(array))  # Minimum element
print(np.std(array))  # Standard deviation
print(np.var(array))  # Variance of all elements
print(np.median(array))  # Median of all elements
print(np.percentile(array, 50))  # 50th percentile (median)
print(np.percentile(array, 25))  # 25th percentile
print(np.percentile(array, 75))  # 75th percentile
print(np.argmax(array))  # Index of the maximum element
print(np.argmin(array))  # Index of the minimum element

55
5.5
10
1
2.8722813232690143
8.25
5.5
5.5
3.25
7.75
9
0


In [24]:
import numpy as np
ages = np.array([
    [21,17,19,20,16,30,18,65],
    [39,22,15,99,18,19,20,21],
])

teenagers = ages[ages < 20]
print("Teenage ages:", teenagers)

adults = ages[(ages >= 20) & (ages < 60)]
print("Adult ages:", adults)

seniors = ages[ages >= 60]
print("Senior ages:", seniors)

teenagers = np.where(ages < 20, ages, 0)
print("Teenagers (using np.where):\n", teenagers)

Teenage ages: [17 19 16 18 15 18 19]
Adult ages: [21 20 30 39 22 20 21]
Senior ages: [65 99]
Teenagers (using np.where):
 [[ 0 17 19  0 16  0 18  0]
 [ 0  0 15  0 18 19  0  0]]


In [25]:
import numpy as np

rng = np.random.default_rng(seed=1)

print(rng.integers(low = 1, high = 101, size=(5,5)))

[[48 52 76 96  4]
 [15 83 95 25 32]
 [87 43 28 83 26]
 [41 65 55  9  3]
 [87 76 84 54 82]]


In [26]:
import numpy as np
rng = np.random.default_rng()

array = np.array([1,2,3,4,5])
fruits = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])

rng.shuffle(array)

fruit = rng.choice(fruits)
print(array)
print("Selected fruit:", fruit)

[5 4 1 3 2]
Selected fruit: cherry
